//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECTION
    {
        public int INSPECTIONID { get; set; }
        public int INSPECTION_STATUS_ID { get; set; }
        public int INSPECTIONTYPEID { get; set; }
        public int RENTALAGREEMENTID { get; set; }
        public Nullable<System.DateTime> INSPECTIONDATETIME { get; set; }
        public string INSPECTIONNOTE { get; set; }
    
        public virtual INSPECTIONTYPE INSPECTIONTYPE { get; set; }
        public virtual INSPECTIONSTATU INSPECTIONSTATU { get; set; }
        public virtual RENTAL_AGREEMENT RENTAL_AGREEMENT { get; set; }
    }
}
