//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INF370Entities : DbContext
    {
        public INF370Entities()
            : base("name=INF370Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENT> AGENTs { get; set; }
        public virtual DbSet<AREA> AREAs { get; set; }
        public virtual DbSet<BOOKING> BOOKINGs { get; set; }
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<COMPLAINT> COMPLAINTs { get; set; }
        public virtual DbSet<COMPLAINTSTATU> COMPLAINTSTATUS { get; set; }
        public virtual DbSet<DATE> DATEs { get; set; }
        public virtual DbSet<DATETIMESLOT> DATETIMESLOTs { get; set; }
        public virtual DbSet<DEACTIVATEDUSER> DEACTIVATEDUSERs { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENTs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<EMPLOYEEDATETIMESLOT> EMPLOYEEDATETIMESLOTs { get; set; }
        public virtual DbSet<EMPLOYEESLOTSTATU> EMPLOYEESLOTSTATUS { get; set; }
        public virtual DbSet<EMPLOYEETYPE> EMPLOYEETYPEs { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public virtual DbSet<INSPECTION> INSPECTIONs { get; set; }
        public virtual DbSet<INSPECTIONSTATU> INSPECTIONSTATUS { get; set; }
        public virtual DbSet<INSPECTIONTYPE> INSPECTIONTYPEs { get; set; }
        public virtual DbSet<ITEM> ITEMs { get; set; }
        public virtual DbSet<JOB> JOBs { get; set; }
        public virtual DbSet<JOBSTATU> JOBSTATUS { get; set; }
        public virtual DbSet<JOBTASK> JOBTASKs { get; set; }
        public virtual DbSet<JOBTYPE> JOBTYPEs { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<PAYMENTTYPE> PAYMENTTYPEs { get; set; }
        public virtual DbSet<PROPERTY> PROPERTies { get; set; }
        public virtual DbSet<PROPERTYPHOTO> PROPERTYPHOTOes { get; set; }
        public virtual DbSet<PROPERTYSTATU> PROPERTYSTATUS { get; set; }
        public virtual DbSet<PROPERTYTYPE> PROPERTYTYPEs { get; set; }
        public virtual DbSet<PROVINCE> PROVINCEs { get; set; }
        public virtual DbSet<PURCHASE> PURCHASEs { get; set; }
        public virtual DbSet<PURCHASELINE> PURCHASELINEs { get; set; }
        public virtual DbSet<RENTAL_AGREEMENT> RENTAL_AGREEMENT { get; set; }
        public virtual DbSet<RENTAL_STATUS> RENTAL_STATUS { get; set; }
        public virtual DbSet<RENTALAMOUNT> RENTALAMOUNTs { get; set; }
        public virtual DbSet<RENTALAPPLICATION> RENTALAPPLICATIONs { get; set; }
        public virtual DbSet<RENTALAPPLICATIONSTATU> RENTALAPPLICATIONSTATUS { get; set; }
        public virtual DbSet<RENTALPERIOD> RENTALPERIODs { get; set; }
        public virtual DbSet<SLOT> SLOTs { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public virtual DbSet<TERMINATEDAGREEMENT> TERMINATEDAGREEMENTs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USERTYPE> USERTYPEs { get; set; }
    }
}
